In [1]:
!pip install scipy



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
from scipy import integrate

# Define a simple function
def integrand(x):
    return x**2

# Compute the integral of the function
result, _ = integrate.quad(integrand, 0, 1)
print("Integral of x^2 from 0 to 1:", result)

Integral of x^2 from 0 to 1: 0.33333333333333337


In [19]:
data = np.arange(float(100) )


In [20]:
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [ ]:
# calculer la moyenne avec Numpy
moyenne = np.mean(data)

In [22]:
moyenne

np.float64(49.5)

In [ ]:
# Calculer l'ecart avec NNP
ecart = np.std(data)

In [24]:
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [25]:
import scipy.stats as stats
# Calcul de la moyenne avec SciPy
moyenne_SP = stats.tmean(data)

In [26]:
moyenne_SP

np.float64(49.5)

In [29]:
# Calcul de l'écart avec SciPy
ecart_SP = stats.tstd(data)

In [30]:
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [31]:
import pandas as pd

In [33]:
stock_price = np.random.seed(0)

In [34]:
stock_price

In [35]:
dates = pd.date_range(start='2023-01-01', periods=100)
prices = np.random.normal(loc=100, scale=10, size=len(dates))

In [36]:
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
      

In [37]:
stock_data = pd.DataFrame({
    'Date': dates,
    'DVLPRS_Price': prices })

In [38]:
# Displaying the first few rows of the simulated data
print(stock_data.head())

        Date  DVLPRS_Price
0 2023-01-01    117.640523
1 2023-01-02    104.001572
2 2023-01-03    109.787380
3 2023-01-04    122.408932
4 2023-01-05    118.675580


In [41]:
stock_data['DVLPRS_Price']

0     117.640523
1     104.001572
2     109.787380
3     122.408932
4     118.675580
         ...    
95    107.065732
96    100.105000
97    117.858705
98    101.269121
99    104.019894
Name: DVLPRS_Price, Length: 100, dtype: float64

In [42]:
stock_data['DVLPRS_Price'].to_numpy()

array([117.64052346, 104.00157208, 109.78737984, 122.40893199,
       118.6755799 ,  90.2272212 , 109.50088418,  98.48642792,
        98.96781148, 104.10598502, 101.44043571, 114.54273507,
       107.61037725, 101.21675016, 104.43863233, 103.33674327,
       114.94079073,  97.94841736, 103.13067702,  91.45904261,
        74.47010184, 106.53618595, 108.64436199,  92.5783498 ,
       122.69754624,  85.45634325, 100.45758517,  98.1281615 ,
       115.32779214, 114.6935877 , 101.54947426, 103.7816252 ,
        91.12214252,  80.19203532,  96.52087851, 101.56348969,
       112.30290681, 112.02379849,  96.12673183,  96.97697249,
        89.51447035,  85.79982063,  82.93729809, 119.50775395,
        94.90347818,  95.61925698,  87.4720464 , 107.77490356,
        83.86102152,  97.8725972 ,  91.04533439, 103.86902498,
        94.89194862,  88.19367816,  99.71817772, 104.28331871,
       100.66517222, 103.02471898,  93.65677906,  96.37258834,
        93.27539552,  96.40446838,  91.86853718,  82.73

In [51]:
format_dates = np.datetime_as_string(dates, unit='D')

In [52]:
format_dates

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
       '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
       '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
       '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
       '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
       '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
       '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
       '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
       '2023-03-02', '2023-03-03', '2023-03-04', '2023-

In [ ]:

# 🌟 Exercise 4 : Data Manipulation with NumPy and Pandas

In [ ]:
df = pd.DataFrame()

In [2]:
import numpy as np
from scipy import stats

# Example data
x = np.array([2, 4, 6, 8, 10])
y = np.array([3, 5, 7, 9, 11])

# Performing linear regression
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)

# The slope and intercept of the regression line
print("Slope:", slope)
print("Intercept:", intercept)

Slope: 1.0
Intercept: 1.0
