In [2]:
!pip install numpy



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np


In [9]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4 5]


1D Array: [1 2 3 4 5]


In [7]:
print("Shape:", array_1d.shape)


Shape: (4,)


In [10]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# Vérifier le type de la liste 2D
array_2d.dtype

# !!!!!!!! Puisque nous travaillons sur Jupiter, pas besoin de PRINT pour afficher le résultat!!!!!!!!

dtype('int64')

In [ ]:
# Vérifier la diagonale de la liste 2D 
array_2d.diagonal

<function ndarray.diagonal>

In [16]:
# Vérifier la forme de la liste 2D (ici nous avons 2 lignes et 3 colones)
array_2d.shape

(2, 3)

In [18]:
# Vérifier la taille de la liste 2D (ici nous avons 6 éléments dans notre table)

array_2d.size

6

In [ ]:

# Création d'une matrice 1D.   !!! ""Arange vous permmets de créer une liste d'élémnts (int) plus rapindement
array_1d = np.arange(0, 12)

In [20]:
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# redimentionner les colones et des lignes
array_1d.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
array_1d.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
array_1d.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
# array_transposition
